### ISSUE TITLE
Extracting 16S rRNA sequences

### ISSUE THREAD

**Issue by vrbrand** [MadsAlbertsen/mmgenome#26]
Hi,

I'm fairly new to this and was wondering where I could access the gg_90.fasta file used to extract 16S rRNA sequences in the rRNA.sh script.  Is this a reference to the Greengenes database (ie: latest version is gg_13_5) or is it something else entirely?

Thanks so much!

**Comment by Kirk3gaard** [comment]
Hi vrbrand

You can grab it here:
https://dl.dropboxusercontent.com/u/2964658/gg_90.fasta

Yes it is just the GreenGenes database clustered at 90 % sequence identity

**Comment by vrbrand** [comment]
Thanks!
