### ISSUE TITLE
mmplot_locator(p) warning

### ISSUE THREAD

**Issue by pennyhan** [MadsAlbertsen/mmgenome#44]
All other things work fine, any idea to solve the problem below?

Thanks,
Penny

> mmplot_locator(p)
[1] "~Tab  =  c(NaN, NaN, NaN, NaN, NaN)"
[1] "~gc  =  c(NaN, NaN, NaN, NaN, NaN)"
  ~Tab ~gc
1  NaN NaN
2  NaN NaN
3  NaN NaN
4  NaN NaN
5  NaN NaN
Warning messages:
1: In max(xr) : no non-missing arguments to max; returning -Inf
2: In min(xr) : no non-missing arguments to min; returning Inf
3: In min(xr) : no non-missing arguments to min; returning Inf
4: In max(yr) : no non-missing arguments to max; returning -Inf
5: In min(yr) : no non-missing arguments to min; returning Inf
6: In min(yr) : no non-missing arguments to min; returning Inf

**Comment by Kirk3gaard** [comment]
Hi Pennyhan
I recommend that you download the new version --> mmgenome2 (https://github.com/KasperSkytte/mmgenome2). The old mgenome package is no longer being maintained + the new one comes with better documentation and some nice new features.

**Comment by pennyhan** [comment]
Now all good, many thanks!!
